package apply

// Finding codes for apply/diff/rollback reports.
const (
	codeInvalidPackage      = "invalid_package"
	codeInvalidTarget       = "invalid_target"
	codeMissingProjectRoot  = "missing_project_root"
	codeMissingHomeRoot     = "missing_home_root"
	codeDeviceScopeBlocked  = "device_scope_blocked"
	codeUnknownScope        = "unknown_scope"
	codePathCollision       = "path_collision"
	codePathEscape          = "path_escape"
	codeSymlinkTarget       = "symlink_target"
	codeUnreadable          = "unreadable"
	codeApplyIO             = "apply_io"
	codeApplyFailedRollback = "apply_failed_rolled_back"
	codeRollbackIncomplete  = "rollback_incomplete"
	codeMissingDeployment   = "missing_deployment"
	codeMissingBackup       = "missing_backup"
	codeInvalidBackup       = "invalid_backup"
	codeMissingInstallRoot  = "missing_install_root"
	codeMCPNativeFailed     = "mcp_native_failed"
	codeMCPNativeCreated    = "mcp_native_created"
	codeMCPNativeUnchanged  = "mcp_native_unchanged"
	codeMCPNativeSkipped    = "mcp_native_skipped"
	codeHookInvalid         = "hook_invalid"
	codeHookPolicy          = "hook_policy"
	codeApplyJournalPresent = "apply_journal_present"
	codeStaleStage          = "stale_stage"
	codeDeploymentInvalid   = "deployment_invalid"
	codeDeploymentDrift     = "deployment_drift"
	codeDriftUnavailable    = "drift_unavailable"
	codeMCPConfigSymlink    = "mcp_config_symlink"
	codeMCPConfigInvalid    = "mcp_config_invalid"
	codeMCPEmptyArgs        = "mcp_empty_args"
)
